name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # يتم تشغيل العملية يومياً
  workflow_dispatch: # يسمح بتشغيل العملية يدوياً

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v2
        with:
          github_user_name: ChaimaaChouhaibi # ضع اسم المستخدم الخاص بك
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push the snake animation
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
