name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # تشغيل يومياً
  workflow_dispatch: # لتشغيله يدوياً

jobs:
  generate:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ChaimaaChouhaibi
          outputs: dist/github-contribution-grid-snake.svg
        
      - name: Push the snake animation
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
          token: ${{ secrets.GH_PAT }}
